### ISSUE TITLE
关于原生插件问题

### ISSUE THREAD

**Issue by arashrun** [tonyfettes/coc-rime#12]
我在coc讨论区里看到发布的一个关于cocinstall插件的时候依赖包中无法执行`postinstall`问题[discussion](https://github.com/neoclide/coc.nvim/discussions/4960)，那个问题最后是如何解决的呢，我在写一个插件也碰到了需要构建node插件的问题

**Comment by Freed-Wu** [comment]
Now it looks like coc.nvim support it https://github.com/neoclide/coc.nvim/pull/5002 although I haven't tested it.

For this project, it use prebuildify to distribute binary library, and run `npm rebuild` when current platform doesn't have binary library.

**Comment by arashrun** [comment]
我用的最新的COC版本，出现这个问题。应该是没解决

**Comment by Freed-Wu** [comment]
I haven't tested https://github.com/neoclide/coc.nvim/pull/5002. If it cannot work, you can ask them :smile:
