### ISSUE TITLE
这是一个很棒的插件，初次体验之后发现一个疑似bug

### ISSUE THREAD

**Issue by denstiny** [tonyfettes/coc-rime#2]
![image](https://user-images.githubusercontent.com/57088952/108074709-7b450380-70a4-11eb-97da-e829e959fa0c.png)

## 要求
- 添加启用和关闭快捷键
- 优先级效果不明显，在coc使用其他的补全插件时，不希望先出现的是中文而是补全的关键字，当然这又回到了第一个问题，是否可以可以启动和关闭的快捷键

**Comment by tonyfettes** [comment]
我觉得我现在可能修复了这个 bug，但是现在它需要使用源码编译的 coc.nvim 才能够完全修复。

您可以参考 coc.nvim 的 README 文件来获取一个使用主分支代码并编译的 coc.nvim 插件。同时，请 `CocUpdate` 来获取本插件的最新版本。 

关于快捷键，我已经为本插件添加了 `CocCommand`，您可以将其映射到您喜欢的快捷键。

关于优先级，我已经将本插件默认补全优先级设为 0，低于一般的补全插件。如果您觉得效果不尽人意，除了暂时禁用，我目前也没什么好的想法。

**Comment by Freed-Wu** [comment]
我个人的使用经验是默认禁用:

```json
  "rime.enabled": false,
  "rime.priority": 99,
```

然后绑定一个快捷键 toggle。比如 `C-6`

```vim
  inoremap <C-^> <C-O>:<C-U>...<CR>
```

toggle 的内容是：

```vim
  " enable/disable Chinese
  CocCommand rime.toggle
  " disable/enable English
  call CocAction('toggleSource', 'word')
  call CocAction('toggleSource', 'coc-zi')
  call CocAction('toggleSource', 'dictionary')
```

这样一开始是补全英文单词，但按 C-6 后就是补全中文输入法。再按一次恢复原样。
