### ISSUE TITLE
关于中文乱码问题

### ISSUE THREAD

**Issue by xiangjs6** [tonyfettes/coc-rime#3]
在neovim中使用coc-rime，当我打出拼音时，可能会出现一些乱码，尝试装了wqy-microhei和wqy-zenhei软件包，都没有效果，系统使用的是manjaro，不知道如何解决这个问题
![图片](https://user-images.githubusercontent.com/43806600/134445645-5b892bb7-9a61-4860-8569-5f0aab9e91cb.png)

**Comment by tonyfettes** [comment]
就我的使用经验来说，Rime 输入法生僻字出现频率会比较高...如果你想显示这些字，可以试着安装一下花园明朝这些涵盖汉字广的字体；但这些生僻字在我的使用场景里并不怎么会用到，所以我之前直接过滤的生僻字，现在使用的是 [clover](https://github.com/fkxxyz/rime-cloverpinyin) 这个输入方案。希望能帮到您。

**Comment by xiangjs6** [comment]
> 
> 
> 就我的使用经验来说，Rime 输入法生僻字出现频率会比较高...如果你想显示这些字，可以试着安装一下花园明朝这些涵盖汉字广的字体；但这些生僻字在我的使用场景里并不怎么会用到，所以我之前直接过滤的生僻字，现在使用的是 [clover](https://github.com/fkxxyz/rime-cloverpinyin) 这个输入方案。希望能帮到您。

谢谢您的回答，我使用pacman安装了cloverpinyin方案，但不知道如何在coc-rime中选择这个方案，我对rime实在是不熟悉，您能告诉我吗如何安装到coc-rime中吗

**Comment by tonyfettes** [comment]
在 `~/.local/share/rime-cli` 下新建/打开 `default.custom.yaml`，确保文件中有以下内容：
```yaml
patch:
  schema_list:
    - schema: clover
```
重新部署 Rime （我用的是 fcitx5 所以我一般直接在系统托盘中重启 fcitx5，其他例如 fcitx 或者 ibus 啥的我也不清楚，或许可以看看 Arch Wiki），不出意外的话就可以用了。

**Comment by xiangjs6** [comment]
> 
> 
> 这两个里面选一个就可以了...
> 
>     1. 在 Vim/Neovim 中直接输入 `:CocList rime_schema`，然后在跳出来的窗口中选择你想要的方案。你也可以在 `coc-settings.json` 中写明你希望的默认的 `schemaId`，例如
> 
> 
> ```js
> {
>   // ...
>   "rime.schemaId": "clover"
>   // ...
> }
> ```
> 
>     1. 在 `~/.local/share/rime-cli` 下新建/打开 `default.custom.yaml`，确保文件中有以下内容：
> 
> 
> ```yaml
> patch:
>   schema_list:
>     - schema: clover
> ```
> 
> 重新部署 Rime （我用的是 fcitx5 所以我一般直接在系统托盘中重启 fcitx5，其他例如 fcitx 或者 ibus 啥的我也不清楚，或许可以看看 Arch Wiki），不出意外的话就可以用了。这样的问题就是 coc-rime 只会有 clover 一个输入方案，如果你需要别的可以在 `schema_list` 下面添加新的键值对，例如
> 
> ```yaml
>     - schema: name
> ```
> 
> 这样。

thx，完美的帮助我配置好了，感谢
