### ISSUE TITLE
Support NixOS

### ISSUE THREAD

**Issue by Freed-Wu** [tonyfettes/coc-rime#6]
This project downloads rime-cli binary for Linux. However, NixOS doesn't support HFS, which means all programs need to be `patchelf`ed:

```shell
patchelf --set-rpath "$(nix eval --impure --expr '"${(import <nixpkgs> {}).stdenv.cc.cc.lib}/lib:${(import <nixpkgs> {}).json_c}/lib:${(import <nixpkgs> {}).librime}/lib"' | jq -r .)" rime-cli
patchelf --set-interpreter $(nix eval --impure --expr '"${(import <nixpkgs> {}).glibc}/lib64/ld-linux-x86-64.so.2"' | jq -r .) rime-cli
```

Maybe these command can be run automatically when this plugin detect current distribution is `NixOS`.

**Comment by tonyfettes** [comment]
Hi, just wondering if you could make an PR, since I'm not using NixOS I have not way to test your solution, plus I'm pretty busy these days, so if I'll be implementing it, it will happen weeks later I guess...
